# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Unit tests
        run: npm run test
        
      - name: Publish unit tests
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: xunit.xml
          check_name: Unit Test Results
          report_individual_runs: true
          comment_on_pr: true
        
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          files: "**/coverage*.json"
          fail_ci_if_error: true
          verbose: true
          flags: unittests
  
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    needs: test
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          
      - name: Install dependencies
        run: yarn --frozen-lockfile
        
      - name: Build app
        run: npm run build
        
      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
  
  docs:
    runs-on: ubuntu-latest
    name: Publish Docs

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile
        
      - name: Generate docs
        run: npm run docs
      
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
          REPOSITORY_NAME: M3L6H/checkers-docs
