# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Unit tests
        run: npm run test
        
      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: coverage
          
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile
        
      - name: Generate docs
        run: npm run docs
      
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
          REPOSITORY_NAME: M3L6H/checkers-docs
